DATABASE:
    DATABASE_NAME: "smart_doc_qa_local"
    HOST: "localhost"
    PORT: 5433

    USER_NAME: "your_local_db_username_here"
    PASSWORD: "your_local_db_password_here"

GROQ_API_KEY:
    API_KEY: "YOUR_GROQ_API_KEY_HERE"
